### ISSUE TITLE
Changes about create and update requests

### ISSUE THREAD

**Issue by yakari007** [nextdeveloper-nl/generator#10]
- [x] This part is not correct. No one should add id or id_ref
- [x] If the field is required but if there is a default value, dont make it required
- [x] created_at, updated_at, deleted_at hiç bir zaman alınmaycak.

![image](https://user-images.githubusercontent.com/95028646/221795743-1fde2899-576a-4486-ab67-22e52ec92e33.png)

**Comment by HuseyinCanAgdelen** [comment]
Needs to be tested @yakari007.
