### ISSUE TITLE
Generate Http requests

### ISSUE THREAD

**Issue by yakari007** [nextdeveloper-nl/generator#9]
According to the database fields, we need to validate the given parameters to any request (such as post and put).

There will be two different requests will be created for two different types;
- post: Since this is a request type to create the object, it will be; "ObjectCreateRequest" under its own folder; "Object"
- put: Since this is an update type of request the name will be; "ObjectUpdateRequest" under its own folder; "Object"

**Comment by HuseyinCanAgdelen** [comment]
Needs to be tested @yakari007.
